### ISSUE TITLE
TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by aequasi** [producthunt/chai-enzyme#120] opened 2016-10-17 19:26 UTC
I know im not giving a ton of information here, but im really not sure what is causing this issue.

I'm using webpack to compile everything

```
        TypeError: Cannot read property 'call' of undefined
            at ReactWrapper.single (webpack:///~/enzyme/build/ReactWrapper.js:1329:0 <- tests.webpack.js:51035:19)
            at ReactTestWrapper.get (webpack:///~/chai-enzyme/build/ReactTestWrapper.js:128:0 <- tests.webpack.js:90179:35)
            at ReactTestWrapper.style (webpack:///~/chai-enzyme/build/ReactTestWrapper.js:61:0 <- tests.webpack.js:90112:19)
            at Assertion.<anonymous> (webpack:///~/chai-enzyme/build/assertions/generic.js:17:0 <- tests.webpack.js:49143:37)
            at Assertion.<anonymous> (webpack:///~/chai-enzyme/build/ChaiWrapper.js:193:0 <- tests.webpack.js:49589:20)
            at Assertion.ctx.(anonymous function) [as style] (webpack:///~/chai/lib/chai/utils/addMethod.js:41:0 <- tests.webpack.js:8460:26)
            at Context.<anonymous> (webpack:///tests/components/Image.test.js:75:57 <- tests.webpack.js:160:59)

```

and the code:
```
const images = [
            '/23649/movie/3/1132905.jpg',
            '/23649/movie/3/1132906.jpg',
            '/23649/movie/3/1132907.jpg'
        ];

        const component = mount(<Image
            image={{url: images[0]}}
            preload={[
                {url: images[1]},
                {url: images[2]}
            ]}
        />);

        expect(component).to.be.present();
        expect(component.find('.current-image')).to.be.present();
        expect(component.find('.current-image')).to.have.style('backgroundImage');
```

The last line there, is line 75 of Image.test.js

**Comment by ayrton** [comment] 2016-10-17 19:33
Upgrade to enzyme 2.5.1 and you should be good to go. Duplicate of #119

**Closed by ayrton** 2016-10-17 19:33 UTC

**Comment by aequasi** [comment] 2016-10-17 19:37
Ah, awesome. Thanks!
