### ISSUE TITLE
React 15.0.0 and Enzyme 3.2.0 issue

### ISSUE THREAD

**Issue by nemanjacosovic** [producthunt/chai-enzyme#212] opened 2017-11-30 20:51 UTC
I'm using "enzyme": "^3.2.0" and today, after installing chai-enzyme I got:

npm WARN chai-enzyme@0.8.0 requires a peer of enzyme@1.x || ^2.3.0 but none is installed. You must install peer dependencies yourself.

**Comment by nemanjacosovic** [comment] 2017-11-30 21:33
After some digging around, and help from @ayrton I've installed beta version which solved the issue.

However, now I have a new one:

**Comment by ljharb** [comment] 2017-11-30 22:12
Duplicate of #211.

**Closed by ljharb** 2017-11-30 22:12 UTC

**Comment by nemanjacosovic** [comment] 2017-12-17 16:31
Solution is to install beta:

npm install --save-dev chai-enzyme@beta
