### ISSUE TITLE
Not compatible with upcoming version of react

### ISSUE THREAD

**Issue by aaron-axisa** [producthunt/chai-enzyme#128] opened 2016-11-09 08:27 UTC
React 15.4.0-rc.4 breaks this library as you were depending on react/lib/ReactTestUtils (which is now under the react-dom package, however it is reccomended to not depend on anything in the /lib directory.

**Comment by ayrton** [comment] 2016-11-09 09:13
Duplicate of #117 tldr; this is an issue with https://github.com/algolia/react-element-to-jsx-string/issues/56

**Closed by ayrton** 2016-11-09 09:13 UTC
